### ISSUE TITLE
`packed_simd` benchmark is broken on the latest master

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rustc-perf#765]
This appears to have been broken by https://github.com/rust-lang/rust/pull/76295

Steps to reproduce:
1. Run `rustup-toolchain-install-master 0f9f0b384a0a3c997c1ea8f838f5591f12f96633`
2. Run `cargo +0f9f0b384a0a3c997c1ea8f838f5591f12f96633 check` from the `collector/benchmarks/packed-simd` directory
3. Note the following error:

```
error[E0635]: unknown feature `mmx_target_feature`
   --> src/lib.rs:212:5
    |
212 |     mmx_target_feature,
    |     ^^^^^^^^^^^^^^^^^^
```

This is currently causes issues with perf runs. No indication is being given that this job is failing - instead, it's just not showing up on `https://perf.rust-lang.org` at all.

**Comment by Mark-Simulacrum** [comment]
https://perf.rust-lang.org/status.html notes the problem. I do see that it's missing in the comparison page, that's an oversight that should get fixed.

I fixed the packed-simd crate now though and it should get picked up in the next build.

**Comment by rylev** [comment]
@Mark-Simulacrum Can this be closed? This issue seems to be fixed

**Comment by Mark-Simulacrum** [comment]
Yes, indeed.
